CREATE TABLE ss_form_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    phonenumber VARCHAR(20),
    comments TEXT,
    location VARCHAR(255)
);