name: github actions demo
on: [push]

defaults:
  run:
    shell: bash -xef {0}

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        run: |
          pwd
          git clone --single-branch --branch "$GITHUB_REF_NAME" "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" .

      - name: install java 21 jdk
        run: |
          sudo apt-get -qq install -y openjdk-21-{jdk,jre}
          javac --version
          sudo update-java-alternatives --list || true
          sudo update-java-alternatives --set java-1.21.0-openjdk-amd64
          javac --version

      - name: install just
        run: |
          pushd /tmp
          wget --quiet https://github.com/casey/just/releases/download/1.36.0/just-1.36.0-x86_64-unknown-linux-musl.tar.gz
          tar xf just-1.36.0-x86_64-unknown-linux-musl.tar.gz just
          mkdir -p $HOME/.local/bin 
          mv just $HOME/.local/bin
          rm just-1.36.0-x86_64-unknown-linux-musl.tar.gz
          popd

      - name: build project
        run: |
          pwd
          tree
          echo $JAVA_HOME
          just build
