name: github actions demo
on: [push]
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - run: |
          pwd
          ls -l
          git clone --depth 1 "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"

      # install just
      - run: |
          wget --quiet https://github.com/casey/just/releases/download/1.36.0/just-1.36.0-x86_64-unknown-linux-musl.tar.gz
          tar xf just-1.36.0-x86_64-unknown-linux-musl.tar.gz just
          mkdir -p $HOME/.local/bin 
          mv just $HOME/.local/bin

      - run: |
          pwd
          ls -l
          tree
          pushd $GITHUB_REPOSITORY   
          just build
